version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: taskmanagement_postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: TaskManagementDB
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
